### ISSUE TITLE
Saving video requires ffmpeg

### ISSUE THREAD

**Issue by porst17** [IMAGINARY/surfer-alggeo-gtk#1]
On Ubuntu 14.04 (and Debian?) distributions, `ffmpeg` is not available in the package repositories anymore (at least I can't find it). I think, they switched to `avconv`. Surfer should provide a compile time option to switch between `avconv` and `ffmpeg` as it seems ffmpeg might return (http://www.webupd8.org/2014/11/ffmpeg-returns-to-official-ubuntu.html). Since saving video is nothing but a `system()` call to `ffmpeg`, it shouldn't be too hard set up equivalent command line options for `avconv`. Then, one of the two packages has to be set a dependency for `surfer-alggeo-gtk`.

**Comment by jgmbenoit** [comment]
As ffmpeg and avconv seem interchangeable, while they may be both present in Jessie+1 and in Ubuntu, their presence is now checked on the fly at execution time (in that order for the default setting). On the apt packaging side, both ffmpeg and libav-tools will be recommended.
At the end, it will be transparent for the final user.

**Comment by porst17** [comment]
Tested 3978626. Seems to be fixed.
