### ISSUE TITLE
Gallery page selector in fullscreen mode

### ISSUE THREAD

**Issue by porst17** [IMAGINARY/surfer-alggeo-gtk#2]
When a gallery is selected, a pop-up window in opened to select the actual gallery page for a specific surface. In fullscreen mode, this popup is still in windowed mode, i.e. one can see the windows decorations and such. The popup should either be fullscreen as well or removed completely. In the latter case, the gallery chooser should be shown as some kind of overlay to the main window. Something like a stack layout in GTK3. Not sure if there is an equivalent for GTK2.

**Comment by jgmbenoit** [comment]
I have just adapted the existing material to decent solutions for both the full and reduced screen modes. The code has been also a bit clean up. Not surprisingly, new issues have raised. In particular, the transition between the reduced  and full screen modes is broken: I am on my way to fix it.
N.B.: the changes has not been yet brought to the apt packages.

**Comment by jgmbenoit** [comment]
The transition between the reduced and full screen modes has been fixed.
Meanwhile, I realized that some frame menu events seems not managed: the fix of this issue may be postponed as some dead code might be wiped out provided that the adapted `decent solutions' is satisfastory.

**Comment by porst17** [comment]
Tested 3978626. Seems to be fixed.
